version: '3.7'
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    ports:
      - "1080:1080"
      - "1080:1080/udp"
    volumes:
      - ./client-config.json:/etc/v2ray/config.json
    command: ["v2ray", "-config=/etc/v2ray/config.json"]
