version: '3.7'

services:
  rabbitmq:
#    image: rabbitmq:3-management
    image: my-rabbitmq:3.7
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      backend:
        aliases:
          - rabbitmq

networks:
  backend:
    external: true