version: '3.7'
services:
  portainer:
    image: portainer/portainer
    command: ["-H", "unix:///var/run/docker.sock", "--admin-password-file", "/tmp/portainer_password"]
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_password:/tmp/portainer_password
